development:
  adapter: postgresql
  encoding: unicode
  database: rails_react_recipes_development
  pool: 5
  username: gopikrishna
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: rails_react_recipes_test
  pool: 5
  username: gopikrishna
  password: 